GOPH/Models/Alert.cs
namespace GOPH.Models
{
    public class Alert
    {
        public bool IsResult { get; set; }

        public string Message { get; set; }
    }
}

GOPH/Areas/Manager/Controllers/OrderController.cs
using GOPH.ATMapper;
using GOPH.DbContextLayer;
using GOPH.Dto;
using GOPH.Entites;
using GOPH.Extensions;
using GOPH.Models;
using GOPH.Security.Requirements;
using GOPH.Services.CallApiServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using System.Reflection.Metadata.Ecma335;
using System.Runtime.Serialization;

namespace GOPH.Areas.Manager.Controllers
{
    [Area("manager")]
    public class OrderController : BaseController
    {

        private readonly IAuthorizationService _authorizationService;

        private readonly SignInManager<AppUser> _signInManager;

        private readonly UserManager<AppUser> _userManager;
        public OrderController(IMemoryCache cache, 
            AppDbContext appDbContext,
            ILogger<BaseController> logger,
            IHttpClientServiceImplementation httpClientServiceImplementation,
            IAuthorizationService authorizationService,
            SignInManager<AppUser> signInManager,
            UserManager<AppUser> userManager
            ) : base(cache, appDbContext, logger,  httpClientServiceImplementation)
        {
            _authorizationService = authorizationService;
            _signInManager = signInManager;
            _userManager    = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var orders = await _context.Orders.OrderByDescending(x => x.DateCreate)
                .Include(o => o.Invoice)
                .Include(o => o.Voucher)
                .Include(o => o.Customer)
                .Include(o => o.OrderProducts)
                .ThenInclude(o => o.Product)
                .ThenInclude(ob => ob.Wholesale)
                .Include(o => o.Invoice)
                .Include(o => o.AppUser)              
                .Where(o => o.Invoice == null && o.RecycleBin == false)
                .AsNoTracking()
                .ToListAsync();

            foreach (var order in orders)
            {
             
                if (order.AppUser is null)
                {
                    continue;
                   
                }

                var user = await _signInManager.CreateUserPrincipalAsync(order.AppUser);
                var IsAu = await _authorizationService.AuthorizeAsync(user, null,
                                               new CanOptionWholesaleRequirements());

                foreach (var item in order.OrderProducts)
                {
                    if (!IsAu.Succeeded)
                    {
                        continue;
                    }

                    if (item.Product.Wholesale is null)
                    {
                        continue;
                    }

                    item.Product.Price = item.Product.Wholesale.Price;
                    item.Product.Promotion = item.Product.Wholesale.Promotion;

                }
            }

            var orderDetails = ObjectMapper.Mapper.Map<List<OrderDetailDto>>(orders);

            var datetimeNow = DateTime.Now;
            foreach (var order in orderDetails)
            {
                order.ConvertDatetime = ConvertDatetime.GetConvert(datetimeNow, order.DateCreate);
                order.DatetimeDetail = ConvertDatetime.GetDateTime(order.DateCreate);

                order.TotalPrice = order.OrderProducts
                    .Sum(c => (c.Product.Price * c.Quantity) - (c.Product.Price * (c.Product.Promotion * c.Quantity) / 100));

                if (order.Voucher != null)
                {
                    order.TotalPrice -= order.Voucher.Price;
                }
            }

            return View(orderDetails);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            var order = await _context.Orders
                .Include(o => o.Invoice)
                .Include(o => o.Voucher)
                .Include(o=> o.Customer)
                .Include(o => o.AppUser)
                .Include(o => o.OrderProducts)
                .ThenInclude(o => o.Product)
                .ThenInclude(ob => ob.Wholesale)
                .FirstOrDefaultAsync(x => x.Id == id);

            var orderDetail = ObjectMapper.Mapper.Map<OrderDetailDto>(order);

            if (orderDetail.AppUser != null)
                {

                    var user = await _signInManager.CreateUserPrincipalAsync(orderDetail.AppUser);
                    var IsAu = await _authorizationService.AuthorizeAsync(user, null,
                                                   new CanOptionWholesaleRequirements());

                    foreach (var item in orderDetail.OrderProducts)
                    {
                        if (!IsAu.Succeeded)
                        {
                            continue;
                        }

                        if (item.Product.Wholesale is null)
                        {
                            continue;
                        }

                        item.Product.Price = item.Product.Wholesale.Price;
                        item.Product.Promotion = item.Product.Wholesale.Promotion;
                        item.IsWholesale = true;
                    }

                }

            var datetimeNow = DateTime.Now;

            orderDetail.ConvertDatetime = ConvertDatetime.GetConvert(datetimeNow, order.DateCreate);
            orderDetail.DatetimeDetail = ConvertDatetime.GetDateTime(order.DateCreate);

            orderDetail.TotalPrice = order.OrderProducts
                .Sum(c => (c.Product.Price * c.Quantity) - (c.Product.Price * (c.Product.Promotion * c.Quantity) / 100));

            if (order.Voucher != null)
            {
                orderDetail.TotalPrice -= order.Voucher.Price;
            }
            return View(orderDetail);
        }

        [HttpPost]
        public async Task<IActionResult> CloseTheOrder([FromRoute]string id)
        {
            var order = await _context.Orders.FindAsync(id);

            if (order is null)
            {
                return NotFound($"Không tìm thấy Id đơn hàng {id}");
            }

            try
            {
                order.IsCloseTheOrder = !order.IsCloseTheOrder;

                await _context.SaveChangesAsync();

                if (order.IsCloseTheOrder)
                {
                    StatusMessage = $"Chốt đơn hàng {order.Id} thàng công";
                }
                else
                {
                    StatusMessage = $"Bỏ chốt đơn hàng {order.Id} thàng công";
                }

                return RedirectToAction("detail", new {id = order.Id});
            }
            catch (Exception)
            {
                return NotFound("Lỗi hệ thống thủ lại hoặc liên hệ admin sdt: 0355445775");
            }
        }


        [HttpGet]
        public async Task<IActionResult> RecycleBin()
        {
            var orders = await _context.Orders.OrderByDescending(x => x.DateCreate)
                .Include(o => o.Invoice)
                .Include(o => o.Voucher)
                .Include(o => o.Customer)
                .Include(o => o.OrderProducts)
                .ThenInclude(o => o.Product)
                .ThenInclude(ob => ob.Wholesale)
                .Include(o => o.Invoice)
                .Include(o => o.AppUser)
                .Where(o => o.Invoice == null && o.RecycleBin == true)
                .AsNoTracking()
                .ToListAsync();

            foreach (var order in orders)
            {

                if (order.AppUser is null)
                {
                    continue;

                }

                var user = await _signInManager.CreateUserPrincipalAsync(order.AppUser);
                var IsAu = await _authorizationService.AuthorizeAsync(user, null,
                                               new CanOptionWholesaleRequirements());

                foreach (var item in order.OrderProducts)
                {
                    if (!IsAu.Succeeded)
                    {
                        continue;
                    }

                    if (item.Product.Wholesale is null)
                    {
                        continue;
                    }

                    item.Product.Price = item.Product.Wholesale.Price;
                    item.Product.Promotion = item.Product.Wholesale.Promotion;

                }
            }

            var orderDetails = ObjectMapper.Mapper.Map<List<OrderDetailDto>>(orders);

            var datetimeNow = DateTime.Now;
            foreach (var order in orderDetails)
            {
                order.ConvertDatetime = ConvertDatetime.GetConvert(datetimeNow, order.DateCreate);
                order.DatetimeDetail = ConvertDatetime.GetDateTime(order.DateCreate);

                order.TotalPrice = order.OrderProducts
                    .Sum(c => (c.Product.Price * c.Quantity) - (c.Product.Price * (c.Product.Promotion * c.Quantity) / 100));

                if (order.Voucher != null)
                {
                    order.TotalPrice -= order.Voucher.Price;
                }
            }

            return View(orderDetails);
        }
        [HttpPost]
        public async Task<IActionResult> CancelToRecycleBin(string id)
        {
            var order = await _context.Orders.FirstAsync(o => o.Id == id);

            if (order == null)
            {
                return NotFound($"Không tìm thấy id đơn hàng {id}");
            }
                   
            try
            {

                order.RecycleBin = true;

                //_context.Customers.Remove(order.Customer);

                await _context.SaveChangesAsync();

                StatusMessage = $"Bỏ thùng rác thành công đơn hàng {order.Id}";

                return RedirectToAction("Index");
            }
            catch (Exception)
            {

GOPH/Controllers/WholesaleShowController.cs
using GOPH.DbContextLayer;
using GOPH.Entites;
using GOPH.Paging;
using GOPH.Services.CallApiServices;
using GOPH.Services.CartServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;

namespace GOPH.Controllers
{
    public class WholesaleShowController : BaseController
    {
        public WholesaleShowController(IMemoryCache cache, AppDbContext appDbContext, ILogger<BaseController> logger, IHttpContextAccessor httpContextAccessor, ICartServices cartServices, IHttpClientServiceImplementation clientServiceImplementation, IAuthorizationService authorizationService) : base(cache, appDbContext, logger, httpContextAccessor, cartServices, clientServiceImplementation, authorizationService)
        {
        }

        public class ViewModel
        {
            public string GroupId { get; set; }

            public List<string> listSerialUrl { get; set; }

            public IEnumerable<CommodityGroup> Groups { get; set; }

            public PagedList<Wholesale> ProductWholesales { get; set; }

            public string ReturnUrl { get; set; }

        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var groups = await GetCommodidtyGroups();

            var viewModel = new ViewModel()
            {
                listSerialUrl = new List<string>(),
                Groups = groups.ToList(),
                ReturnUrl = Domain()
            };

            var wholesaleParameters = new WholesaleParameters();
           
            viewModel.ProductWholesales = PagedList<Wholesale>
                .ToPagedList(_context.Wholesales
                .Include(p => p.Product)
                .ThenInclude(p => p.Commodity)
                , wholesaleParameters.PageNumber, wholesaleParameters.PageSize);

            return View(viewModel);
        }
    }
}

GOPH/Views/Shared/_Alert.cshtml
@model Alert

@{
    var alert = Model;
    var backgound = "";

    if (alert.IsResult)
    {
        backgound = "alert-success";
    }else
    {
        backgound = "alert-warning";
    }
}

<div class="alert @backgound alert-dismissible fade show" role="alert">
    <strong>
        @if (alert.IsResult)
        {
            <i class="bi bi-check-all text-success"></i>
        }else
        {
            <i class="bi bi-exclamation-triangle text-secondary"></i>
        }
    </strong> @alert.Message
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

GOPH/Views/Shared/_AlertMessage.cshtml
@model string
@{
    var alert = Model;
}

@if (!string.IsNullOrEmpty(alert))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Thông báo </strong> @Model
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

GOPH/Views/Shared/_CardWholesaleProducts.cshtml
@model PagedList<Wholesale>
@{
    var format = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
}

@foreach (var item in Model)
{
    <div class="product-card">
        
        <div class="badge-hot">Giá sỉ</div>
      

        @if (@item.Promotion > 0)
        {
            <div class="discount-product">
                @String.Format("{0}{1}{2}","-", @item.Promotion,"%")
            </div>
        }
        <div class="product-tumb">
            @if (item.Product.Images?.Count > 0)
            {
                <a asp-area="" asp-controller="home" asp-action="detail" asp-route-id="@item.Product.Id"><img src="~/ImageManager/ProductImg/@item.Product.Images.ToList()[0].Url" alt=""></a>
            }
            else if (!string.IsNullOrEmpty(item.Product.UrlImage))
            {
                <a asp-area="" asp-controller="home" asp-action="detail" asp-route-id="@item.Product.Id"><img src="@item.Product.UrlImage" alt=""></a>

            }
            else
            {
                <a asp-area="" asp-controller="home" asp-action="detail" asp-route-id="@item.Product.Id"><img src="~/image/goph.jpg" /></a>

            }
        </div>
        <div class="product-details">
            <span class="product-catagory">@item.Product.CommodityGroup?.Name</span>
            <h4><a asp-area="" asp-controller="home" asp-action="detail" asp-route-id="@item.Product.Id">@item.Product.Name</a></h4>

            <div class="product-bottom-details">
                <div class="product-price">
                    @if (item.Product.IsPrice)
                    {
                      
                       <small>@String.Format(format, "{0:c0}", @item.Product.Price )</small>
                        

                    }
                   
                    @String.Format(format, "{0:c0}", @item.Price )
      

                </div>
                <div class="product-links">
                    <a><i class="bi bi-chat-heart"></i></a>
                    <a onclick="addtocart(this,`@item.Product.Id`)"><i class="bi bi-bag-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
}

GOPH/Views/Shared/_DropPaginPartial.cshtml
@model Pagin

@{
    int currentPage = Model.CurrentPage;
    int countPages = Model.TotalPages;
    Func<int?, string> generateUrl;
    var urlAction = Model.UrlAction;
    if (Model.IsPage)
    {
        generateUrl = (int? _pagenumber) =>
        {
            return Url.Page(urlAction, new { pagenumber = _pagenumber });
        };
    }
    else
    {
        generateUrl = (int? _pagenumber) =>
        {
            return Url.Action(urlAction, new { pagenumber = _pagenumber });
        };
    }

    if (currentPage > countPages)
        currentPage = countPages;

    if (countPages <= 1) return;


    
    int? next = null;

    if (currentPage < countPages)
        next = currentPage + 1;


}


<ul class="show-drop-post">
    @if (next != null)
    {
        <li  onclick="showDrop(this)" value="@next">
            <a id="loadingshowpost"> <span aria-hidden="true"><i class="bi bi-mouse2"></i> Xem thêm </span></a>
        </li>
    }
    else
    {
        <li>
            <a href="#" tabindex="-1" aria-disabled="true">Hết <i class="bi bi-arrow-up-short"></i></a>
        </li>
    }
</ul>

GOPH/Views/Shared/_ItemCartPartial.cshtml
@using GOPH.Dto;
@model IEnumerable<ProductCart>

@{
    var format = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");

    var productPromotions = Model.Where(x => x.Promotion != 0).ToList();

    var picePromotion = 0;
    
    foreach (var item in productPromotions)
    {
        picePromotion += ((int)item.TotalPrice * item.Promotion) / 100;

        
    }

    var totalallpriceCurent = Model.Sum(x => x.TotalPrice);

    var totalallprice = totalallpriceCurent - picePromotion;

}


  
<div class="products">
        @if (Model?.Count() > 0)
        {
            @foreach (var item in Model)
            {
                <div class="product">

                    @if (item.Images?.Count > 0)
                    {
                        <img src="~/ImageManager/ProductImg/@item.Images.ToList()[0].Url" alt="">
                    }
                    else if (!string.IsNullOrEmpty(item.UrlImage))
                    {
                        <img src="@item.UrlImage" alt="">

                    }
                    else
                    {
                       <img src="~/image/goph.jpg" />

                    }

                    <div class="product-info">

                        <h3 class="product-name">@item.Name</h3>

                        <h5 class="product-price">
                            Đơn : @String.Format(format, "{0:c0}", item.Price )
                            @if (item.isWholesale)
                            {
                                <span style="color: red; font-size: 16px;"> (Giá sỉ)</span>
                            }
                        </h5>
                        <h5 class="product-offer">Giảm: @item.Promotion %</h5>
                        <h5 class="product-price">Tổng : @String.Format(format, "{0:c0}", item.TotalPrice  -  item.TotalPrice * item.Promotion /100 )</h5>
                            <div class="counter" >
                                <button onClick='decreaseCount(`@item.Id`, this)' class="minus-btn" type="button" name="button">
                                    -
                                </button>

                                <input type="number" name="name" value="@item.Quantity">
                                <button onClick='increaseCount(`@item.Id`, this)' class="plus-btn" type="button" name="button">
                                    +
                                </button>
                            </div>
                        <div>
                            <button class="product-remove" onclick='deletCart(this, `@item.Id`)'> <i class="bi bi-trash3-fill"></i></button>
                        </div>
                       
                     
                    </div>

                </div>
            }
        }
        else
        {
            <div class="cart-default">
                <p>
                    Chưa có sản phẩm trong giỏ hàng <a asp-area="" asp-controller="home" asp-action="index">Tới cửa hàng</a>
                </p>
                <a asp-area="" asp-controller="home" asp-action="index"><img src="~/logo/go-pharmacy.png" /></a>
            </div>

        }
</div>





<div class="cart-total">

    <p>

        <span>Tổng tiền:</span>

        <span> @String.Format(format, "{0:c0}", totalallpriceCurent )</span>

    </p>

    <p>

        <span>Giảm giá trực tiếp :</span>

        <span>@String.Format(format, "{0:c0}", picePromotion )</span>

    </p>

    <p>

        <span>Thành tiền :</span>

        <span>@String.Format(format, "{0:c0}", totalallprice )</span>

    </p>
    @if (Model?.Count() > 0)
    {
        <a asp-area="" asp-action="OrderInformation" asp-controller="cart">Đặt hàng</a>
    }
    

</div>

GOPH/Views/Shared/_LayOutOrderManager.cshtml
@inject IHttpContextAccessor _httpcontext;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var domain = string.Format("{0}://{1}", _httpcontext.HttpContext.Request.Scheme, _httpcontext.HttpContext.Request.Host.ToString());
    var statusMessage = TempData["StatusMessage"] as string;
}

<div class="container mt-2">
    <input type="hidden" id="domain" value="@domain" />
    <input type="hidden" id="number-page" value="1" />
    <div class="category-order">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link @ActiveNavPages.OrderActiveClass(ViewContext)" asp-area="manager" asp-controller="order" asp-action="index"><i class="bi bi-box2"></i> Đơn đặt hàng</a>
            </li>
            <li class="nav-item">
                <a class="nav-link @ActiveNavPages.InvoiceActiveClass(ViewContext) " asp-area="manager" asp-controller="Invoice" asp-action="index"><i class="bi bi-receipt-cutoff"></i> Hóa đơn</a>
            </li>
            <li class="nav-item">
                <a class="nav-link @ActiveNavPages.OrderRecycleBinActiveClass(ViewContext) " asp-area="manager" asp-controller="order" asp-action="recyclebin"><i class="bi bi-trash3-fill"></i> Đơn hàng rác</a>
            </li>
            
        </ul>
    </div>

    <partial name="_AlertMessage" model="@statusMessage" />
    
    @RenderBody()

    <div class="myAlert-bottom alert alert-primary" role="alert">
    </div>
    <div id="modal-all" class="modal-all">
        <div class="loadding-all"><img style="width: 50px; height:50px;" src="~/iconcontan/load.gif" /></div>
    </div>

</div>

@section Scripts{

    @await RenderSectionAsync("Scripts", required: false)

}

GOPH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GOPH</title>

    @await RenderSectionAsync("FacebookSharedHead", required: false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GOPH.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css"
      rel="Stylesheet" type="text/css" />
    <link href="~/css/navbar-search.css" rel="stylesheet" />
    <link href="~/css/detail-product.css" rel="stylesheet" />
    <link href="~/css/alert.css" rel="stylesheet" />
    <link href="~/css/cart.css" rel="stylesheet" />
    @await RenderSectionAsync("ImageManager", required: false)

    @RenderSection("BannerEvent", required: false)

    
</head>
<body>
    <header>
        <nav  class="header navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">                   
                    <img width="60" height="auto" src="~/logo/go-pharmacy.png" class="header_logo header-logo" alt="Nhà Thuốc GO – Hệ Thống Nhà Thuốc Lớn Tại Nha Trang">

                </a>
               
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Thông tin</a>
                        </li>
                        @await Html.PartialAsync("_WholesalePartial")
                    </ul>
                    <ul class="navbar-nav manager">
                        @await Html.PartialAsync("_ManagerPartial")

                    </ul>

                    @await Html.PartialAsync("_LoginPartial")
                </div>
               
            </div>
        </nav>
        @await RenderSectionAsync("NavbarTop", required: false)
      
        
    </header>
    <div class="container-lg">
        <main role="main" id="main">
            @RenderBody()
        </main>
    </div>
    @await RenderSectionAsync("HostPhone", required: false)
    <footer class="border-top footer text-muted">

        <div class="container">
            &copy; 2023 - GOPH - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/microsoft-signalr/signalr.js"></script>
    <script src="~/js/internal-message.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GOPH/Views/Shared/_LayoutManagerProduct.cshtml
@inject IHttpContextAccessor _httpcontext
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var domain = string.Format("{0}://{1}", _httpcontext.HttpContext.Request.Scheme, _httpcontext.HttpContext.Request.Host.ToString());
    var statusMessage = TempData["StatusMessage"] as string;
}

<div class="container mt-2">
    <input type="hidden" id="domain" value="@domain" />
    <input type="hidden" id="number-page" value="1" />
    <partial name="_AlertMessage" model="@statusMessage" />

    <div class="container">
        <div class="row">
            <div class="col-md-3">
               
                <div class="list-group  mt-2">
                    <h5 class="list-group-item my-0"> Danh mục quản lý </h5>
                    <a class="list-group-item @ActiveNavPages.ProductActiveClass(ViewContext) " asp-area="manager" asp-controller="product" asp-action="index">
                            Sản phẩm & thuốc
                        </a>
                    <a class="list-group-item @ActiveNavPages.GroupActiveClass(ViewContext) " asp-area="manager" asp-controller="commodityGroup" asp-action="index">
                             Nhóm
                        </a>
                    <a class="list-group-item @ActiveNavPages.CommodityActiveClass(ViewContext)" asp-area="manager" asp-controller="commodity" asp-action="index">
                            Mặt hàng
                    </a>

                    <a class="list-group-item @ActiveNavPages.EventActiveClass(ViewContext)" asp-area="manager" asp-controller="event" asp-action="index">
                        Sự kiện
                    </a>

                    <a class="list-group-item @ActiveNavPages.CacheActiveClass(ViewContext)" asp-area="manager" asp-controller="cache" asp-action="index">
                            Cache
                     </a>

                </div>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
  

    <div class="myAlert-bottom alert alert-primary" role="alert">
    </div>
    <div id="modal-all" class="modal-all">
        <div class="loadding-all"><img style="width: 50px; height:50px;" src="~/iconcontan/load.gif" /></div>
    </div>

</div>


@section ImageManager{

    <link href="~/css/img-manager.css" rel="stylesheet" />
   

}

@section NavbarTop{


    @await RenderSectionAsync("NavbarTop", required: false)
    
}

@section Scripts{

    @await RenderSectionAsync("Scripts", required: false)

}

GOPH/Views/Shared/_LayoutSummernote.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GOPH </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <div class="container">
        
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/Summernote-cr/popper.min.js"></script>
    <link href="~/Summernote-cr/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Summernote-cr/bootstrap.min.js"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GOPH/Views/Shared/_ManagerPartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
    var resultAuthorization = await authorizationService.AuthorizeAsync(this.User, "Employee");

    var resultAuthorizationManager = await authorizationService.AuthorizeAsync(this.User, "Admin");


}

@if (resultAuthorization.Succeeded)
{

    
}
<li class="nav-item">
    <a class="nav-link" asp-area="manager" asp-controller="Order" asp-action="Index">Đơn hàng @*<span id="mesage-count-order">0</span>*@</a>
</li>


@if (resultAuthorizationManager.Succeeded)
{
    
}
<li class="nav-item dropdown">
    <a class="nav-link" asp-area="Manager" asp-controller="product" asp-action="index">
        Manager
    </a>

</li>

GOPH/Views/Shared/_WholesalePartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
    var resultAuthorization = await authorizationService.AuthorizeAsync(this.User, "Customer");

}


@if (resultAuthorization.Succeeded)
{

}

<li class="nav-item">
    <a asp-area="" asp-action="index" asp-controller="WholesaleShow" class="nav-link text-white">
        Giá sỉ <img style="width: 28px; height: auto;" src="~/iconcontan/hot-icon.gif" />
    </a>
</li>